// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_runs.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const completeAgentRun = `-- name: CompleteAgentRun :one
UPDATE agent_runs
SET status        = 'completed',
    answer        = $2,
    latency_ms    = $3,
    input_tokens  = $4,
    output_tokens = $5,
    finished_at   = now()
WHERE id = $1
RETURNING id, conversation_id, query, status, model, answer, error, latency_ms, input_tokens, output_tokens, created_at, finished_at
`

type CompleteAgentRunParams struct {
	ID           uuid.UUID `json:"id"`
	Answer       *string   `json:"answer"`
	LatencyMs    *int32    `json:"latency_ms"`
	InputTokens  *int32    `json:"input_tokens"`
	OutputTokens *int32    `json:"output_tokens"`
}

func (q *Queries) CompleteAgentRun(ctx context.Context, arg CompleteAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, completeAgentRun,
		arg.ID,
		arg.Answer,
		arg.LatencyMs,
		arg.InputTokens,
		arg.OutputTokens,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Query,
		&i.Status,
		&i.Model,
		&i.Answer,
		&i.Error,
		&i.LatencyMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const failAgentRun = `-- name: FailAgentRun :one
UPDATE agent_runs
SET status      = 'failed',
    error       = $2,
    latency_ms  = $3,
    finished_at = now()
WHERE id = $1
RETURNING id, conversation_id, query, status, model, answer, error, latency_ms, input_tokens, output_tokens, created_at, finished_at
`

type FailAgentRunParams struct {
	ID        uuid.UUID `json:"id"`
	Error     *string   `json:"error"`
	LatencyMs *int32    `json:"latency_ms"`
}

func (q *Queries) FailAgentRun(ctx context.Context, arg FailAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, failAgentRun, arg.ID, arg.Error, arg.LatencyMs)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Query,
		&i.Status,
		&i.Model,
		&i.Answer,
		&i.Error,
		&i.LatencyMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertAgentRun = `-- name: InsertAgentRun :one
INSERT INTO agent_runs (conversation_id, query, status, model)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, query, status, model, answer, error, latency_ms, input_tokens, output_tokens, created_at, finished_at
`

type InsertAgentRunParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Query          string    `json:"query"`
	Status         string    `json:"status"`
	Model          *string   `json:"model"`
}

func (q *Queries) InsertAgentRun(ctx context.Context, arg InsertAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, insertAgentRun,
		arg.ConversationID,
		arg.Query,
		arg.Status,
		arg.Model,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Query,
		&i.Status,
		&i.Model,
		&i.Answer,
		&i.Error,
		&i.LatencyMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}
