// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_runs.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeAgentRun = `-- name: CompleteAgentRun :one
UPDATE agent_runs
SET status        = 'completed',
    answer        = $2,
    latency_ms    = $3,
    input_tokens  = $4,
    output_tokens = $5,
    finished_at   = now()
WHERE id = $1
RETURNING id, conversation_id, query, status, model, answer, error, latency_ms, input_tokens, output_tokens, created_at, finished_at
`

type CompleteAgentRunParams struct {
	ID           uuid.UUID `json:"id"`
	Answer       *string   `json:"answer"`
	LatencyMs    *int32    `json:"latency_ms"`
	InputTokens  *int32    `json:"input_tokens"`
	OutputTokens *int32    `json:"output_tokens"`
}

func (q *Queries) CompleteAgentRun(ctx context.Context, arg CompleteAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, completeAgentRun,
		arg.ID,
		arg.Answer,
		arg.LatencyMs,
		arg.InputTokens,
		arg.OutputTokens,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Query,
		&i.Status,
		&i.Model,
		&i.Answer,
		&i.Error,
		&i.LatencyMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const countUserRunsSince = `-- name: CountUserRunsSince :one
SELECT count(*) FROM agent_runs r
         JOIN conversations c ON c.id = r.conversation_id
WHERE c.user_id = $1 AND r.created_at > $2
`

type CountUserRunsSinceParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Per-user rate limit: the shared cost of a run is Satyam's upstream
// API quotas even when the LLM spend is the user's. $2 is a timestamp rather
// than a hardcoded interval so tests can pin the window.
func (q *Queries) CountUserRunsSince(ctx context.Context, arg CountUserRunsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserRunsSince, arg.UserID, arg.CreatedAt)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const failAgentRun = `-- name: FailAgentRun :one
UPDATE agent_runs
SET status      = 'failed',
    error       = $2,
    latency_ms  = $3,
    finished_at = now()
WHERE id = $1
RETURNING id, conversation_id, query, status, model, answer, error, latency_ms, input_tokens, output_tokens, created_at, finished_at
`

type FailAgentRunParams struct {
	ID        uuid.UUID `json:"id"`
	Error     *string   `json:"error"`
	LatencyMs *int32    `json:"latency_ms"`
}

func (q *Queries) FailAgentRun(ctx context.Context, arg FailAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, failAgentRun, arg.ID, arg.Error, arg.LatencyMs)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Query,
		&i.Status,
		&i.Model,
		&i.Answer,
		&i.Error,
		&i.LatencyMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getAgentRun = `-- name: GetAgentRun :one
SELECT id, conversation_id, query, status, model, answer, error, latency_ms, input_tokens, output_tokens, created_at, finished_at FROM agent_runs WHERE id = $1
`

func (q *Queries) GetAgentRun(ctx context.Context, id uuid.UUID) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getAgentRun, id)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Query,
		&i.Status,
		&i.Model,
		&i.Answer,
		&i.Error,
		&i.LatencyMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getAgentRunForUser = `-- name: GetAgentRunForUser :one
SELECT r.id, r.conversation_id, r.query, r.status, r.model, r.answer, r.error, r.latency_ms, r.input_tokens, r.output_tokens, r.created_at, r.finished_at FROM agent_runs r
         JOIN conversations c ON c.id = r.conversation_id
WHERE r.id = $1 AND c.user_id = $2
`

type GetAgentRunForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Ownership is enforced in the query, not in Go: GET /api/runs/{id} takes a
// caller-supplied UUID, and joining through conversations is what stops it
// being an IDOR the moment a second user exists.
func (q *Queries) GetAgentRunForUser(ctx context.Context, arg GetAgentRunForUserParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, getAgentRunForUser, arg.ID, arg.UserID)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Query,
		&i.Status,
		&i.Model,
		&i.Answer,
		&i.Error,
		&i.LatencyMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getAgentRunOwner = `-- name: GetAgentRunOwner :one
SELECT c.user_id FROM agent_runs r
         JOIN conversations c ON c.id = r.conversation_id
WHERE r.id = $1
`

// Runs don't carry a user_id; ownership lives on the conversation. The worker
// resolves the owner to build the run's LLM provider from their stored key.
func (q *Queries) GetAgentRunOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getAgentRunOwner, id)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const insertAgentRun = `-- name: InsertAgentRun :one
INSERT INTO agent_runs (conversation_id, query, status, model)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, query, status, model, answer, error, latency_ms, input_tokens, output_tokens, created_at, finished_at
`

type InsertAgentRunParams struct {
	ConversationID uuid.UUID `json:"conversation_id"`
	Query          string    `json:"query"`
	Status         string    `json:"status"`
	Model          *string   `json:"model"`
}

func (q *Queries) InsertAgentRun(ctx context.Context, arg InsertAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, insertAgentRun,
		arg.ConversationID,
		arg.Query,
		arg.Status,
		arg.Model,
	)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Query,
		&i.Status,
		&i.Model,
		&i.Answer,
		&i.Error,
		&i.LatencyMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const listResumableStalledRuns = `-- name: ListResumableStalledRuns :many
SELECT r.id FROM agent_runs r
WHERE r.status = 'awaiting_approval'
  AND NOT EXISTS (
    SELECT 1 FROM agent_actions a
    WHERE a.agent_run_id = r.id
      AND a.status IN ('pending', 'approved', 'executing')
  )
ORDER BY r.id
LIMIT $1
`

// The liveness backstop: runs paused for a decision that has already been made.
//
// A run reaches this state only through a bug — the lock above is what prevents
// it — but "the investigation never answers and nothing in the system can find
// it" is a bad enough outcome to warrant a cheap sweep that cannot be reasoned
// wrong. Ordered by id so a batch locks runs in a deterministic order.
func (q *Queries) ListResumableStalledRuns(ctx context.Context, limit int32) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listResumableStalledRuns, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAgentRunForSettlement = `-- name: LockAgentRunForSettlement :one
SELECT id FROM agent_runs WHERE id = $1 FOR UPDATE
`

// Serializes the settle-and-resume decision for one run.
//
// Every path that settles an action asks, in the same transaction, "is anything
// on this run still outstanding?" and enqueues the resume only when the answer
// is no. Under READ COMMITTED that question is unsafe when two actions on one
// run are settled concurrently: each transaction sees its own settlement plus
// the OTHER row in its pre-commit state, so both count one outstanding action
// and neither enqueues a resume. The run then sits in 'awaiting_approval'
// forever — the expiry sweep only looks at 'pending' rows, so nothing would
// ever find it again.
//
// Taking this lock as the first statement of each settling transaction makes
// those transactions run one at a time per run, so the second one sees the
// first's committed settlement and enqueues exactly one resume. It locks the
// run row rather than using an advisory lock so the lock is released by COMMIT
// with no separate unlock to leak.
func (q *Queries) LockAgentRunForSettlement(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, lockAgentRunForSettlement, id)
	var id_2 uuid.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const pauseAgentRun = `-- name: PauseAgentRun :one
UPDATE agent_runs
SET status        = 'awaiting_approval',
    input_tokens  = $2,
    output_tokens = $3
WHERE id = $1
  AND status = 'running'
RETURNING id, conversation_id, query, status, model, answer, error, latency_ms, input_tokens, output_tokens, created_at, finished_at
`

type PauseAgentRunParams struct {
	ID           uuid.UUID `json:"id"`
	InputTokens  *int32    `json:"input_tokens"`
	OutputTokens *int32    `json:"output_tokens"`
}

// running -> awaiting_approval. The status guard keeps the transition honest for
// a run that raced to a terminal state; no rows means there is nothing to pause.
//
// finished_at stays NULL: the run is not finished, it is waiting. Token totals
// are stored so a paused run's cost is visible before it resumes, and because a
// resume rebuilds them from the event log rather than from memory.
func (q *Queries) PauseAgentRun(ctx context.Context, arg PauseAgentRunParams) (AgentRun, error) {
	row := q.db.QueryRow(ctx, pauseAgentRun, arg.ID, arg.InputTokens, arg.OutputTokens)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Query,
		&i.Status,
		&i.Model,
		&i.Answer,
		&i.Error,
		&i.LatencyMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const resumeAgentRun = `-- name: ResumeAgentRun :one
UPDATE agent_runs
SET status = 'running'
WHERE id = $1
  AND status IN ('awaiting_approval', 'running')
RETURNING id, conversation_id, query, status, model, answer, error, latency_ms, input_tokens, output_tokens, created_at, finished_at
`

// awaiting_approval -> running, claiming a paused run for the resume job.
//
// 'running' is admitted alongside 'awaiting_approval' for the same reason
// StartAgentRun admits it: a resume job retried after its worker was killed
// mid-loop must be able to pick the run back up. Anything terminal matches
// nothing, so a run that already answered cannot be resumed into a second life.
func (q *Queries) ResumeAgentRun(ctx context.Context, id uuid.UUID) (AgentRun, error) {
	row := q.db.QueryRow(ctx, resumeAgentRun, id)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Query,
		&i.Status,
		&i.Model,
		&i.Answer,
		&i.Error,
		&i.LatencyMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}

const startAgentRun = `-- name: StartAgentRun :one
UPDATE agent_runs
SET status = 'running'
WHERE id = $1
  AND status IN ('pending', 'running')
RETURNING id, conversation_id, query, status, model, answer, error, latency_ms, input_tokens, output_tokens, created_at, finished_at
`

// Claims a queued run. The status guard makes the transition idempotent for a
// River job that is retried after a worker crash (still 'running'), while
// refusing to restart a run that already reached a terminal state — returning
// no rows is the signal to skip.
func (q *Queries) StartAgentRun(ctx context.Context, id uuid.UUID) (AgentRun, error) {
	row := q.db.QueryRow(ctx, startAgentRun, id)
	var i AgentRun
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Query,
		&i.Status,
		&i.Model,
		&i.Answer,
		&i.Error,
		&i.LatencyMs,
		&i.InputTokens,
		&i.OutputTokens,
		&i.CreatedAt,
		&i.FinishedAt,
	)
	return i, err
}
