// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: agent_actions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const approveAgentAction = `-- name: ApproveAgentAction :one
UPDATE agent_actions
SET status       = 'approved',
    final_payload = $2,
    decided_by   = $3,
    decided_at   = now()
WHERE id = $1
  AND user_id = $5
  AND status = 'pending'
  AND proposed_at > $4
RETURNING id, agent_run_id, user_id, source, action, proposed_payload, final_payload, status, idempotency_key, reject_reason, result, error, proposed_at, decided_at, executed_at, decided_by
`

type ApproveAgentActionParams struct {
	ID           uuid.UUID          `json:"id"`
	FinalPayload []byte             `json:"final_payload"`
	DecidedBy    *uuid.UUID         `json:"decided_by"`
	ProposedAt   pgtype.Timestamptz `json:"proposed_at"`
	UserID       uuid.UUID          `json:"user_id"`
}

// pending -> approved, storing the payload that will actually execute.
//
// The user_id predicate is the ownership guard. The handler also reads the row
// for the caller first, so this is belt and braces today — but the guarantee
// "one person cannot decide another person's write" belongs in the statement
// that performs the decision, not only in the handler that happens to call it.
// A future caller that forgets the pre-read is then a no-op, not a breach.
//
// The status guard is the concurrency control: two simultaneous approvals both
// read a pending row, both issue this UPDATE, and exactly one matches. The
// loser gets no rows, which the handler reports as "already decided" instead of
// enqueueing a second execution.
//
// The TTL guard sits in the same predicate rather than in a prior SELECT for the
// same reason: checked separately, a row could expire between the check and the
// write. $4 is the cutoff timestamp — passed in rather than computed from an
// interval here so the configured TTL stays in one place and tests can pin it.
func (q *Queries) ApproveAgentAction(ctx context.Context, arg ApproveAgentActionParams) (AgentAction, error) {
	row := q.db.QueryRow(ctx, approveAgentAction,
		arg.ID,
		arg.FinalPayload,
		arg.DecidedBy,
		arg.ProposedAt,
		arg.UserID,
	)
	var i AgentAction
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.UserID,
		&i.Source,
		&i.Action,
		&i.ProposedPayload,
		&i.FinalPayload,
		&i.Status,
		&i.IdempotencyKey,
		&i.RejectReason,
		&i.Result,
		&i.Error,
		&i.ProposedAt,
		&i.DecidedAt,
		&i.ExecutedAt,
		&i.DecidedBy,
	)
	return i, err
}

const beginExecutingAgentAction = `-- name: BeginExecutingAgentAction :one
UPDATE agent_actions
SET status = 'executing'
WHERE id = $1
  AND status = 'approved'
RETURNING id, agent_run_id, user_id, source, action, proposed_payload, final_payload, status, idempotency_key, reject_reason, result, error, proposed_at, decided_at, executed_at, decided_by
`

// approved -> executing. This is the compare-and-set that makes execution
// exactly-once: the execution job claims the row before it touches the upstream
// API, so a retry of that job — or a duplicate enqueue — finds the row no longer
// 'approved', matches nothing, and returns without sending anything.
func (q *Queries) BeginExecutingAgentAction(ctx context.Context, id uuid.UUID) (AgentAction, error) {
	row := q.db.QueryRow(ctx, beginExecutingAgentAction, id)
	var i AgentAction
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.UserID,
		&i.Source,
		&i.Action,
		&i.ProposedPayload,
		&i.FinalPayload,
		&i.Status,
		&i.IdempotencyKey,
		&i.RejectReason,
		&i.Result,
		&i.Error,
		&i.ProposedAt,
		&i.DecidedAt,
		&i.ExecutedAt,
		&i.DecidedBy,
	)
	return i, err
}

const countExecutedActionsSince = `-- name: CountExecutedActionsSince :one
SELECT count(*) FROM agent_actions
WHERE user_id = $1
  AND COALESCE(executed_at, decided_at) > $2
  AND status IN ('executing', 'executed')
`

type CountExecutedActionsSinceParams struct {
	UserID uuid.UUID          `json:"user_id"`
	Since  pgtype.Timestamptz `json:"since"`
}

// The per-user hourly write limit. Counted on rows that reached (or are
// reaching) the upstream system — 'executing' is included deliberately, so a
// burst of in-flight writes cannot slip past a count that only sees finished
// ones.
//
// The window is anchored on when the write went OUT, not on when it was
// proposed. A proposal may sit pending for the whole ACTION_TTL (24h by
// default), so counting by proposed_at would leave the ceiling bypassable:
// approve a day's worth of aged proposals and every one of them executes within
// a minute while counting as zero against the hour. What the limit exists to
// bound is how much mail actually leaves the account, so that is what it counts.
//
// An 'executing' row has no executed_at yet and falls back to decided_at:
// approval is the moment execution is set in motion, which keeps in-flight
// writes inside the window without letting a row stuck mid-execution hold the
// ceiling down forever.
//
// sqlc.arg(since) is a timestamp rather than a hardcoded interval so tests can
// pin the window, matching the run limit's query.
func (q *Queries) CountExecutedActionsSince(ctx context.Context, arg CountExecutedActionsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExecutedActionsSince, arg.UserID, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnsettledActionsByRun = `-- name: CountUnsettledActionsByRun :one
SELECT count(*) FROM agent_actions
WHERE agent_run_id = $1
  AND status IN ('pending', 'approved', 'executing')
`

// How many of the run's actions have not reached a terminal state.
//
// 'approved' and 'executing' count alongside 'pending', and that is the whole
// point of the query. A run resumes only when every proposal is genuinely
// finished — counting only 'pending' would let a run resume the instant the last
// decision was made, while an approved email was still being sent, and the agent
// would report "approved, outcome unknown" instead of "sent, here is the message
// id". Waiting the extra second buys a truthful answer.
func (q *Queries) CountUnsettledActionsByRun(ctx context.Context, agentRunID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnsettledActionsByRun, agentRunID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const expireAgentAction = `-- name: ExpireAgentAction :one
UPDATE agent_actions
SET status     = 'expired',
    decided_at = now()
WHERE id = $1
  AND status = 'pending'
RETURNING id, agent_run_id, user_id, source, action, proposed_payload, final_payload, status, idempotency_key, reject_reason, result, error, proposed_at, decided_at, executed_at, decided_by
`

// pending -> expired. An expired proposal can never execute.
func (q *Queries) ExpireAgentAction(ctx context.Context, id uuid.UUID) (AgentAction, error) {
	row := q.db.QueryRow(ctx, expireAgentAction, id)
	var i AgentAction
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.UserID,
		&i.Source,
		&i.Action,
		&i.ProposedPayload,
		&i.FinalPayload,
		&i.Status,
		&i.IdempotencyKey,
		&i.RejectReason,
		&i.Result,
		&i.Error,
		&i.ProposedAt,
		&i.DecidedAt,
		&i.ExecutedAt,
		&i.DecidedBy,
	)
	return i, err
}

const failAgentAction = `-- name: FailAgentAction :one
UPDATE agent_actions
SET status      = 'failed',
    error       = $2,
    executed_at = now()
WHERE id = $1
  AND status = 'executing'
RETURNING id, agent_run_id, user_id, source, action, proposed_payload, final_payload, status, idempotency_key, reject_reason, result, error, proposed_at, decided_at, executed_at, decided_by
`

type FailAgentActionParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

// executing -> failed. Terminal: the row is not returned to 'approved' for
// another attempt, because a failed write may or may not have landed upstream
// and re-sending on a guess is the one outcome worse than reporting the failure.
func (q *Queries) FailAgentAction(ctx context.Context, arg FailAgentActionParams) (AgentAction, error) {
	row := q.db.QueryRow(ctx, failAgentAction, arg.ID, arg.Error)
	var i AgentAction
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.UserID,
		&i.Source,
		&i.Action,
		&i.ProposedPayload,
		&i.FinalPayload,
		&i.Status,
		&i.IdempotencyKey,
		&i.RejectReason,
		&i.Result,
		&i.Error,
		&i.ProposedAt,
		&i.DecidedAt,
		&i.ExecutedAt,
		&i.DecidedBy,
	)
	return i, err
}

const failInterruptedAgentAction = `-- name: FailInterruptedAgentAction :one
UPDATE agent_actions
SET status      = 'failed',
    error       = $2,
    executed_at = now()
WHERE id = $1
  AND status = 'executing'
RETURNING id, agent_run_id, user_id, source, action, proposed_payload, final_payload, status, idempotency_key, reject_reason, result, error, proposed_at, decided_at, executed_at, decided_by
`

type FailInterruptedAgentActionParams struct {
	ID    uuid.UUID `json:"id"`
	Error *string   `json:"error"`
}

// executing -> failed, for a write whose worker died mid-attempt.
//
// Distinct from FailAgentAction only in intent, and worth its own name: this one
// records that the outcome is UNKNOWN rather than that the call returned an
// error. The write may well have landed upstream, so it must never be retried,
// and the person who approved it needs to be told exactly that.
func (q *Queries) FailInterruptedAgentAction(ctx context.Context, arg FailInterruptedAgentActionParams) (AgentAction, error) {
	row := q.db.QueryRow(ctx, failInterruptedAgentAction, arg.ID, arg.Error)
	var i AgentAction
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.UserID,
		&i.Source,
		&i.Action,
		&i.ProposedPayload,
		&i.FinalPayload,
		&i.Status,
		&i.IdempotencyKey,
		&i.RejectReason,
		&i.Result,
		&i.Error,
		&i.ProposedAt,
		&i.DecidedAt,
		&i.ExecutedAt,
		&i.DecidedBy,
	)
	return i, err
}

const finishAgentAction = `-- name: FinishAgentAction :one
UPDATE agent_actions
SET status      = 'executed',
    result      = $2,
    executed_at = now()
WHERE id = $1
  AND status = 'executing'
RETURNING id, agent_run_id, user_id, source, action, proposed_payload, final_payload, status, idempotency_key, reject_reason, result, error, proposed_at, decided_at, executed_at, decided_by
`

type FinishAgentActionParams struct {
	ID     uuid.UUID `json:"id"`
	Result []byte    `json:"result"`
}

// executing -> executed, recording what the upstream system returned.
func (q *Queries) FinishAgentAction(ctx context.Context, arg FinishAgentActionParams) (AgentAction, error) {
	row := q.db.QueryRow(ctx, finishAgentAction, arg.ID, arg.Result)
	var i AgentAction
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.UserID,
		&i.Source,
		&i.Action,
		&i.ProposedPayload,
		&i.FinalPayload,
		&i.Status,
		&i.IdempotencyKey,
		&i.RejectReason,
		&i.Result,
		&i.Error,
		&i.ProposedAt,
		&i.DecidedAt,
		&i.ExecutedAt,
		&i.DecidedBy,
	)
	return i, err
}

const getAgentAction = `-- name: GetAgentAction :one
SELECT id, agent_run_id, user_id, source, action, proposed_payload, final_payload, status, idempotency_key, reject_reason, result, error, proposed_at, decided_at, executed_at, decided_by FROM agent_actions WHERE id = $1
`

// By id alone, for the execution job: it runs on behalf of the row's own owner
// rather than a request, so there is no caller identity to check it against.
// Every endpoint a user can reach uses GetAgentActionForUser instead.
func (q *Queries) GetAgentAction(ctx context.Context, id uuid.UUID) (AgentAction, error) {
	row := q.db.QueryRow(ctx, getAgentAction, id)
	var i AgentAction
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.UserID,
		&i.Source,
		&i.Action,
		&i.ProposedPayload,
		&i.FinalPayload,
		&i.Status,
		&i.IdempotencyKey,
		&i.RejectReason,
		&i.Result,
		&i.Error,
		&i.ProposedAt,
		&i.DecidedAt,
		&i.ExecutedAt,
		&i.DecidedBy,
	)
	return i, err
}

const getAgentActionByIdempotencyKey = `-- name: GetAgentActionByIdempotencyKey :one
SELECT id, agent_run_id, user_id, source, action, proposed_payload, final_payload, status, idempotency_key, reject_reason, result, error, proposed_at, decided_at, executed_at, decided_by FROM agent_actions WHERE idempotency_key = $1
`

func (q *Queries) GetAgentActionByIdempotencyKey(ctx context.Context, idempotencyKey string) (AgentAction, error) {
	row := q.db.QueryRow(ctx, getAgentActionByIdempotencyKey, idempotencyKey)
	var i AgentAction
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.UserID,
		&i.Source,
		&i.Action,
		&i.ProposedPayload,
		&i.FinalPayload,
		&i.Status,
		&i.IdempotencyKey,
		&i.RejectReason,
		&i.Result,
		&i.Error,
		&i.ProposedAt,
		&i.DecidedAt,
		&i.ExecutedAt,
		&i.DecidedBy,
	)
	return i, err
}

const getAgentActionForUser = `-- name: GetAgentActionForUser :one
SELECT id, agent_run_id, user_id, source, action, proposed_payload, final_payload, status, idempotency_key, reject_reason, result, error, proposed_at, decided_at, executed_at, decided_by FROM agent_actions WHERE id = $1 AND user_id = $2
`

type GetAgentActionForUserParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

// Ownership is enforced in the query, not in Go: the approve and reject
// endpoints take a caller-supplied UUID, and this predicate is what stops one
// user approving another's pending email.
func (q *Queries) GetAgentActionForUser(ctx context.Context, arg GetAgentActionForUserParams) (AgentAction, error) {
	row := q.db.QueryRow(ctx, getAgentActionForUser, arg.ID, arg.UserID)
	var i AgentAction
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.UserID,
		&i.Source,
		&i.Action,
		&i.ProposedPayload,
		&i.FinalPayload,
		&i.Status,
		&i.IdempotencyKey,
		&i.RejectReason,
		&i.Result,
		&i.Error,
		&i.ProposedAt,
		&i.DecidedAt,
		&i.ExecutedAt,
		&i.DecidedBy,
	)
	return i, err
}

const insertAgentAction = `-- name: InsertAgentAction :one
INSERT INTO agent_actions (agent_run_id, user_id, source, action, proposed_payload, idempotency_key)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (idempotency_key) DO NOTHING
RETURNING id, agent_run_id, user_id, source, action, proposed_payload, final_payload, status, idempotency_key, reject_reason, result, error, proposed_at, decided_at, executed_at, decided_by
`

type InsertAgentActionParams struct {
	AgentRunID      uuid.UUID `json:"agent_run_id"`
	UserID          uuid.UUID `json:"user_id"`
	Source          string    `json:"source"`
	Action          string    `json:"action"`
	ProposedPayload []byte    `json:"proposed_payload"`
	IdempotencyKey  string    `json:"idempotency_key"`
}

// Records a proposal. ON CONFLICT DO NOTHING on the idempotency key rather than
// an upsert: a colliding insert means this exact action was already proposed for
// this run — an agent-run job retried after a crash mid-loop re-proposes
// identically — and the existing row, which may already have been decided, must
// win. No rows returned is the caller's signal to fetch and reuse it.
func (q *Queries) InsertAgentAction(ctx context.Context, arg InsertAgentActionParams) (AgentAction, error) {
	row := q.db.QueryRow(ctx, insertAgentAction,
		arg.AgentRunID,
		arg.UserID,
		arg.Source,
		arg.Action,
		arg.ProposedPayload,
		arg.IdempotencyKey,
	)
	var i AgentAction
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.UserID,
		&i.Source,
		&i.Action,
		&i.ProposedPayload,
		&i.FinalPayload,
		&i.Status,
		&i.IdempotencyKey,
		&i.RejectReason,
		&i.Result,
		&i.Error,
		&i.ProposedAt,
		&i.DecidedAt,
		&i.ExecutedAt,
		&i.DecidedBy,
	)
	return i, err
}

const listAgentActionsByRun = `-- name: ListAgentActionsByRun :many
SELECT id, agent_run_id, user_id, source, action, proposed_payload, final_payload, status, idempotency_key, reject_reason, result, error, proposed_at, decided_at, executed_at, decided_by FROM agent_actions WHERE agent_run_id = $1 ORDER BY proposed_at, id
`

func (q *Queries) ListAgentActionsByRun(ctx context.Context, agentRunID uuid.UUID) ([]AgentAction, error) {
	rows, err := q.db.Query(ctx, listAgentActionsByRun, agentRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentAction{}
	for rows.Next() {
		var i AgentAction
		if err := rows.Scan(
			&i.ID,
			&i.AgentRunID,
			&i.UserID,
			&i.Source,
			&i.Action,
			&i.ProposedPayload,
			&i.FinalPayload,
			&i.Status,
			&i.IdempotencyKey,
			&i.RejectReason,
			&i.Result,
			&i.Error,
			&i.ProposedAt,
			&i.DecidedAt,
			&i.ExecutedAt,
			&i.DecidedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentActionsForUser = `-- name: ListAgentActionsForUser :many
SELECT id, agent_run_id, user_id, source, action, proposed_payload, final_payload, status, idempotency_key, reject_reason, result, error, proposed_at, decided_at, executed_at, decided_by FROM agent_actions
WHERE user_id = $1
ORDER BY proposed_at DESC, id
LIMIT $2
`

type ListAgentActionsForUserParams struct {
	UserID uuid.UUID `json:"user_id"`
	Limit  int32     `json:"limit"`
}

// The audit view: every action across every run, newest first.
func (q *Queries) ListAgentActionsForUser(ctx context.Context, arg ListAgentActionsForUserParams) ([]AgentAction, error) {
	rows, err := q.db.Query(ctx, listAgentActionsForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentAction{}
	for rows.Next() {
		var i AgentAction
		if err := rows.Scan(
			&i.ID,
			&i.AgentRunID,
			&i.UserID,
			&i.Source,
			&i.Action,
			&i.ProposedPayload,
			&i.FinalPayload,
			&i.Status,
			&i.IdempotencyKey,
			&i.RejectReason,
			&i.Result,
			&i.Error,
			&i.ProposedAt,
			&i.DecidedAt,
			&i.ExecutedAt,
			&i.DecidedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredPendingActions = `-- name: ListExpiredPendingActions :many
SELECT id, agent_run_id, user_id, source, action, proposed_payload, final_payload, status, idempotency_key, reject_reason, result, error, proposed_at, decided_at, executed_at, decided_by FROM agent_actions
WHERE status = 'pending' AND proposed_at <= $1
ORDER BY proposed_at
LIMIT $2
`

type ListExpiredPendingActionsParams struct {
	ProposedAt pgtype.Timestamptz `json:"proposed_at"`
	Limit      int32              `json:"limit"`
}

// The expiry sweep's input: pending rows past the TTL cutoff ($1).
func (q *Queries) ListExpiredPendingActions(ctx context.Context, arg ListExpiredPendingActionsParams) ([]AgentAction, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingActions, arg.ProposedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentAction{}
	for rows.Next() {
		var i AgentAction
		if err := rows.Scan(
			&i.ID,
			&i.AgentRunID,
			&i.UserID,
			&i.Source,
			&i.Action,
			&i.ProposedPayload,
			&i.FinalPayload,
			&i.Status,
			&i.IdempotencyKey,
			&i.RejectReason,
			&i.Result,
			&i.Error,
			&i.ProposedAt,
			&i.DecidedAt,
			&i.ExecutedAt,
			&i.DecidedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectAgentAction = `-- name: RejectAgentAction :one
UPDATE agent_actions
SET status        = 'rejected',
    reject_reason = $2,
    decided_by    = $3,
    decided_at    = now()
WHERE id = $1
  AND user_id = $4
  AND status = 'pending'
RETURNING id, agent_run_id, user_id, source, action, proposed_payload, final_payload, status, idempotency_key, reject_reason, result, error, proposed_at, decided_at, executed_at, decided_by
`

type RejectAgentActionParams struct {
	ID           uuid.UUID  `json:"id"`
	RejectReason *string    `json:"reject_reason"`
	DecidedBy    *uuid.UUID `json:"decided_by"`
	UserID       uuid.UUID  `json:"user_id"`
}

// pending -> rejected. Terminal for the action; the run continues and the agent
// is told the reason.
func (q *Queries) RejectAgentAction(ctx context.Context, arg RejectAgentActionParams) (AgentAction, error) {
	row := q.db.QueryRow(ctx, rejectAgentAction,
		arg.ID,
		arg.RejectReason,
		arg.DecidedBy,
		arg.UserID,
	)
	var i AgentAction
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.UserID,
		&i.Source,
		&i.Action,
		&i.ProposedPayload,
		&i.FinalPayload,
		&i.Status,
		&i.IdempotencyKey,
		&i.RejectReason,
		&i.Result,
		&i.Error,
		&i.ProposedAt,
		&i.DecidedAt,
		&i.ExecutedAt,
		&i.DecidedBy,
	)
	return i, err
}

const setUserConnectionWrites = `-- name: SetUserConnectionWrites :execrows
UPDATE user_connections
SET writes_enabled = $3, updated_at = now()
WHERE user_id = $1 AND source = $2
`

type SetUserConnectionWritesParams struct {
	UserID        uuid.UUID `json:"user_id"`
	Source        string    `json:"source"`
	WritesEnabled bool      `json:"writes_enabled"`
}

// Enabling or disabling writes for one source. execrows, not exec: zero rows
// means the connection does not exist, which the handler answers with a 404
// rather than a silent success.
func (q *Queries) SetUserConnectionWrites(ctx context.Context, arg SetUserConnectionWritesParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserConnectionWrites, arg.UserID, arg.Source, arg.WritesEnabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
