// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: citations.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertCitation = `-- name: InsertCitation :one
INSERT INTO citations (agent_run_id, evidence_id, marker, claim_text)
VALUES ($1, $2, $3, $4)
RETURNING id, agent_run_id, evidence_id, marker, claim_text, created_at
`

type InsertCitationParams struct {
	AgentRunID uuid.UUID `json:"agent_run_id"`
	EvidenceID uuid.UUID `json:"evidence_id"`
	Marker     string    `json:"marker"`
	ClaimText  *string   `json:"claim_text"`
}

func (q *Queries) InsertCitation(ctx context.Context, arg InsertCitationParams) (Citation, error) {
	row := q.db.QueryRow(ctx, insertCitation,
		arg.AgentRunID,
		arg.EvidenceID,
		arg.Marker,
		arg.ClaimText,
	)
	var i Citation
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.EvidenceID,
		&i.Marker,
		&i.ClaimText,
		&i.CreatedAt,
	)
	return i, err
}

const listCitationsByRun = `-- name: ListCitationsByRun :many
SELECT c.id,
       c.marker,
       c.claim_text,
       c.created_at,
       e.id  AS evidence_id,
       e.seq AS evidence_seq,
       e.source,
       e.external_id,
       e.title,
       e.url,
       e.snippet,
       e.source_timestamp
FROM citations c
         JOIN evidence e ON e.id = c.evidence_id
WHERE c.agent_run_id = $1
ORDER BY nullif(regexp_replace(c.marker, '\D', '', 'g'), '')::int NULLS LAST, c.marker
`

type ListCitationsByRunRow struct {
	ID              uuid.UUID          `json:"id"`
	Marker          string             `json:"marker"`
	ClaimText       *string            `json:"claim_text"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	EvidenceID      uuid.UUID          `json:"evidence_id"`
	EvidenceSeq     int32              `json:"evidence_seq"`
	Source          string             `json:"source"`
	ExternalID      string             `json:"external_id"`
	Title           *string            `json:"title"`
	Url             *string            `json:"url"`
	Snippet         *string            `json:"snippet"`
	SourceTimestamp pgtype.Timestamptz `json:"source_timestamp"`
}

// Joined with evidence because a citation is only meaningful alongside what it
// points at: the trace endpoint renders the marker, the claim, and the source's
// title and URL together.
// Ordered by the marker's number, not by evidence.seq: the markers are what a
// reader follows through the answer ([1], [2], [3]), while evidence.seq is
// discovery order and does not match. A plain text sort would put [10] before
// [2], hence the cast.
func (q *Queries) ListCitationsByRun(ctx context.Context, agentRunID uuid.UUID) ([]ListCitationsByRunRow, error) {
	rows, err := q.db.Query(ctx, listCitationsByRun, agentRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCitationsByRunRow{}
	for rows.Next() {
		var i ListCitationsByRunRow
		if err := rows.Scan(
			&i.ID,
			&i.Marker,
			&i.ClaimText,
			&i.CreatedAt,
			&i.EvidenceID,
			&i.EvidenceSeq,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Snippet,
			&i.SourceTimestamp,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
