// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: document_chunks.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteChunksByDocument = `-- name: DeleteChunksByDocument :exec
DELETE FROM document_chunks WHERE document_id = $1
`

func (q *Queries) DeleteChunksByDocument(ctx context.Context, documentID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteChunksByDocument, documentID)
	return err
}

const insertDocumentChunk = `-- name: InsertDocumentChunk :exec
INSERT INTO document_chunks (document_id, chunk_index, content, embedding)
VALUES ($1, $2, $3, ($4::text)::vector)
`

type InsertDocumentChunkParams struct {
	DocumentID uuid.UUID `json:"document_id"`
	ChunkIndex int32     `json:"chunk_index"`
	Content    string    `json:"content"`
	Embedding  string    `json:"embedding"`
}

// The embedding arrives as pgvector's text form and is cast in SQL. Passing it
// as text keeps pgx out of the business of knowing the vector type's OID (which
// is dynamic, since vector comes from an extension) at the cost of one cast per
// row on a path that is already dominated by the embedding API call.
func (q *Queries) InsertDocumentChunk(ctx context.Context, arg InsertDocumentChunkParams) error {
	_, err := q.db.Exec(ctx, insertDocumentChunk,
		arg.DocumentID,
		arg.ChunkIndex,
		arg.Content,
		arg.Embedding,
	)
	return err
}

const searchDocumentChunks = `-- name: SearchDocumentChunks :many
SELECT c.id            AS chunk_id,
       c.chunk_index,
       c.content,
       d.id            AS document_id,
       d.source,
       d.external_id,
       d.title,
       d.url,
       d.metadata,
       d.source_timestamp,
       (1 - (c.embedding <=> ($1::text)::vector))::float8 AS similarity
FROM document_chunks c
         JOIN documents d ON d.id = c.document_id
WHERE $2::text IS NULL
   OR d.source = $2::text
ORDER BY c.embedding <=> ($1::text)::vector
LIMIT $3
`

type SearchDocumentChunksParams struct {
	QueryEmbedding string  `json:"query_embedding"`
	Source         *string `json:"source"`
	ResultLimit    int32   `json:"result_limit"`
}

type SearchDocumentChunksRow struct {
	ChunkID         uuid.UUID          `json:"chunk_id"`
	ChunkIndex      int32              `json:"chunk_index"`
	Content         string             `json:"content"`
	DocumentID      uuid.UUID          `json:"document_id"`
	Source          string             `json:"source"`
	ExternalID      string             `json:"external_id"`
	Title           string             `json:"title"`
	Url             string             `json:"url"`
	Metadata        []byte             `json:"metadata"`
	SourceTimestamp pgtype.Timestamptz `json:"source_timestamp"`
	Similarity      float64            `json:"similarity"`
}

// The join is the point (idea.md §11): the vector index finds the chunk, and the
// relational half supplies the title, URL and metadata that make it citable.
// Doing both in one query is only possible because the vectors live in the same
// Postgres as everything else.
//
// <=> is cosine DISTANCE (0 = identical), so similarity is 1 - distance and the
// ordering is ascending. The operator must match the index's vector_cosine_ops
// or the planner silently ignores the index.
func (q *Queries) SearchDocumentChunks(ctx context.Context, arg SearchDocumentChunksParams) ([]SearchDocumentChunksRow, error) {
	rows, err := q.db.Query(ctx, searchDocumentChunks, arg.QueryEmbedding, arg.Source, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SearchDocumentChunksRow{}
	for rows.Next() {
		var i SearchDocumentChunksRow
		if err := rows.Scan(
			&i.ChunkID,
			&i.ChunkIndex,
			&i.Content,
			&i.DocumentID,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Metadata,
			&i.SourceTimestamp,
			&i.Similarity,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
