// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: documents.sql

package store

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countDocuments = `-- name: CountDocuments :one
SELECT count(*) FROM documents
`

// Used to tell "the index is empty" apart from "this query matched nothing",
// which are different answers for the agent: the first means stop searching the
// knowledge base, the second means rephrase.
func (q *Queries) CountDocuments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDocuments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDocumentsBySource = `-- name: CountDocumentsBySource :one
SELECT count(*) FROM documents WHERE source = $1
`

func (q *Queries) CountDocumentsBySource(ctx context.Context, source string) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentsBySource, source)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getDocumentBySourceExternalID = `-- name: GetDocumentBySourceExternalID :one
SELECT id, source, external_id, title, url, content, metadata, content_hash, source_timestamp, created_at, updated_at FROM documents
WHERE source = $1 AND external_id = $2
`

type GetDocumentBySourceExternalIDParams struct {
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetDocumentBySourceExternalID(ctx context.Context, arg GetDocumentBySourceExternalIDParams) (Document, error) {
	row := q.db.QueryRow(ctx, getDocumentBySourceExternalID, arg.Source, arg.ExternalID)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Content,
		&i.Metadata,
		&i.ContentHash,
		&i.SourceTimestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO documents (source, external_id, title, url, content, metadata,
                       content_hash, source_timestamp)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (source, external_id) DO UPDATE
    SET title            = excluded.title,
        url              = excluded.url,
        content          = excluded.content,
        metadata         = excluded.metadata,
        content_hash     = excluded.content_hash,
        source_timestamp = excluded.source_timestamp,
        updated_at       = now()
RETURNING id, source, external_id, title, url, content, metadata, content_hash, source_timestamp, created_at, updated_at
`

type UpsertDocumentParams struct {
	Source          string             `json:"source"`
	ExternalID      string             `json:"external_id"`
	Title           string             `json:"title"`
	Url             string             `json:"url"`
	Content         string             `json:"content"`
	Metadata        []byte             `json:"metadata"`
	ContentHash     string             `json:"content_hash"`
	SourceTimestamp pgtype.Timestamptz `json:"source_timestamp"`
}

// Called only for documents whose content_hash actually changed (the indexer
// short-circuits before this on an unchanged hash), so the update branch always
// has work to do.
func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (Document, error) {
	row := q.db.QueryRow(ctx, upsertDocument,
		arg.Source,
		arg.ExternalID,
		arg.Title,
		arg.Url,
		arg.Content,
		arg.Metadata,
		arg.ContentHash,
		arg.SourceTimestamp,
	)
	var i Document
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Content,
		&i.Metadata,
		&i.ContentHash,
		&i.SourceTimestamp,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
