// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertEvidence = `-- name: InsertEvidence :one
INSERT INTO evidence (agent_run_id, tool_call_id, seq, source, external_id,
                      title, url, snippet, source_timestamp)
SELECT $1::uuid,
       $2::uuid,
       coalesce(max(seq), 0) + 1,
       $3::text,
       $4::text,
       $5::text,
       $6::text,
       $7::text,
       $8::timestamptz
FROM evidence
WHERE agent_run_id = $1::uuid
ON CONFLICT (agent_run_id, source, external_id)
    DO UPDATE SET tool_call_id = evidence.tool_call_id
RETURNING id, agent_run_id, tool_call_id, seq, source, external_id, title, url, snippet, source_timestamp, created_at
`

type InsertEvidenceParams struct {
	AgentRunID      uuid.UUID          `json:"agent_run_id"`
	ToolCallID      *uuid.UUID         `json:"tool_call_id"`
	Source          string             `json:"source"`
	ExternalID      string             `json:"external_id"`
	Title           *string            `json:"title"`
	Url             *string            `json:"url"`
	Snippet         *string            `json:"snippet"`
	SourceTimestamp pgtype.Timestamptz `json:"source_timestamp"`
}

// Per-run evidence numbering plus per-run dedupe in one statement.
//
// The conflict clause is a deliberate no-op update rather than DO NOTHING: the
// caller needs the existing row's seq back so a second tool call that surfaces
// the same document reuses its citation number, and DO NOTHING returns no row at
// all. Assigning tool_call_id to itself keeps "the call that first surfaced this"
// intact.
func (q *Queries) InsertEvidence(ctx context.Context, arg InsertEvidenceParams) (Evidence, error) {
	row := q.db.QueryRow(ctx, insertEvidence,
		arg.AgentRunID,
		arg.ToolCallID,
		arg.Source,
		arg.ExternalID,
		arg.Title,
		arg.Url,
		arg.Snippet,
		arg.SourceTimestamp,
	)
	var i Evidence
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.ToolCallID,
		&i.Seq,
		&i.Source,
		&i.ExternalID,
		&i.Title,
		&i.Url,
		&i.Snippet,
		&i.SourceTimestamp,
		&i.CreatedAt,
	)
	return i, err
}

const listEvidenceByRun = `-- name: ListEvidenceByRun :many
SELECT id, agent_run_id, tool_call_id, seq, source, external_id, title, url, snippet, source_timestamp, created_at FROM evidence
WHERE agent_run_id = $1
ORDER BY seq
`

func (q *Queries) ListEvidenceByRun(ctx context.Context, agentRunID uuid.UUID) ([]Evidence, error) {
	rows, err := q.db.Query(ctx, listEvidenceByRun, agentRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Evidence{}
	for rows.Next() {
		var i Evidence
		if err := rows.Scan(
			&i.ID,
			&i.AgentRunID,
			&i.ToolCallID,
			&i.Seq,
			&i.Source,
			&i.ExternalID,
			&i.Title,
			&i.Url,
			&i.Snippet,
			&i.SourceTimestamp,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
