// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: llm_calls.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const insertLLMCall = `-- name: InsertLLMCall :one
INSERT INTO llm_calls (agent_run_id, purpose, model, input_tokens, output_tokens, latency_ms)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, agent_run_id, purpose, model, input_tokens, output_tokens, latency_ms, created_at
`

type InsertLLMCallParams struct {
	AgentRunID   uuid.UUID `json:"agent_run_id"`
	Purpose      string    `json:"purpose"`
	Model        string    `json:"model"`
	InputTokens  *int32    `json:"input_tokens"`
	OutputTokens *int32    `json:"output_tokens"`
	LatencyMs    *int32    `json:"latency_ms"`
}

func (q *Queries) InsertLLMCall(ctx context.Context, arg InsertLLMCallParams) (LlmCall, error) {
	row := q.db.QueryRow(ctx, insertLLMCall,
		arg.AgentRunID,
		arg.Purpose,
		arg.Model,
		arg.InputTokens,
		arg.OutputTokens,
		arg.LatencyMs,
	)
	var i LlmCall
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.Purpose,
		&i.Model,
		&i.InputTokens,
		&i.OutputTokens,
		&i.LatencyMs,
		&i.CreatedAt,
	)
	return i, err
}
