// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const insertMessage = `-- name: InsertMessage :one
INSERT INTO messages (conversation_id, role, content, agent_run_id)
VALUES ($1, $2, $3, $4)
RETURNING id, conversation_id, role, content, created_at, agent_run_id
`

type InsertMessageParams struct {
	ConversationID uuid.UUID  `json:"conversation_id"`
	Role           string     `json:"role"`
	Content        string     `json:"content"`
	AgentRunID     *uuid.UUID `json:"agent_run_id"`
}

// agent_run_id is null for user messages; the orchestrator sets it on the
// assistant answer so the frontend can reach the run's trace from the message.
func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, insertMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.AgentRunID,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ConversationID,
		&i.Role,
		&i.Content,
		&i.CreatedAt,
		&i.AgentRunID,
	)
	return i, err
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT id, conversation_id, role, content, created_at, agent_run_id FROM messages
WHERE conversation_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListMessagesByConversation(ctx context.Context, conversationID uuid.UUID) ([]Message, error) {
	rows, err := q.db.Query(ctx, listMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
			&i.AgentRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
