// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
	"github.com/pgvector/pgvector-go"
)

type AgentRun struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	Query          string             `json:"query"`
	Status         string             `json:"status"`
	Model          *string            `json:"model"`
	Answer         *string            `json:"answer"`
	Error          *string            `json:"error"`
	LatencyMs      *int32             `json:"latency_ms"`
	InputTokens    *int32             `json:"input_tokens"`
	OutputTokens   *int32             `json:"output_tokens"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

type Citation struct {
	ID         uuid.UUID          `json:"id"`
	AgentRunID uuid.UUID          `json:"agent_run_id"`
	EvidenceID uuid.UUID          `json:"evidence_id"`
	Marker     string             `json:"marker"`
	ClaimText  *string            `json:"claim_text"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Conversation struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     *string            `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Document struct {
	ID              uuid.UUID          `json:"id"`
	Source          string             `json:"source"`
	ExternalID      string             `json:"external_id"`
	Title           string             `json:"title"`
	Url             string             `json:"url"`
	Content         string             `json:"content"`
	Metadata        []byte             `json:"metadata"`
	ContentHash     string             `json:"content_hash"`
	SourceTimestamp pgtype.Timestamptz `json:"source_timestamp"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type DocumentChunk struct {
	ID         uuid.UUID          `json:"id"`
	DocumentID uuid.UUID          `json:"document_id"`
	ChunkIndex int32              `json:"chunk_index"`
	Content    string             `json:"content"`
	Embedding  *pgvector.Vector   `json:"embedding"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type EvalRun struct {
	ID        uuid.UUID          `json:"id"`
	GitSha    string             `json:"git_sha"`
	StartedAt pgtype.Timestamptz `json:"started_at"`
	Metrics   []byte             `json:"metrics"`
}

type Evidence struct {
	ID              uuid.UUID          `json:"id"`
	AgentRunID      uuid.UUID          `json:"agent_run_id"`
	ToolCallID      *uuid.UUID         `json:"tool_call_id"`
	Seq             int32              `json:"seq"`
	Source          string             `json:"source"`
	ExternalID      string             `json:"external_id"`
	Title           *string            `json:"title"`
	Url             *string            `json:"url"`
	Snippet         *string            `json:"snippet"`
	SourceTimestamp pgtype.Timestamptz `json:"source_timestamp"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type LlmCall struct {
	ID           uuid.UUID          `json:"id"`
	AgentRunID   uuid.UUID          `json:"agent_run_id"`
	Purpose      string             `json:"purpose"`
	Model        string             `json:"model"`
	InputTokens  *int32             `json:"input_tokens"`
	OutputTokens *int32             `json:"output_tokens"`
	LatencyMs    *int32             `json:"latency_ms"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	AgentRunID     *uuid.UUID         `json:"agent_run_id"`
}

type RunEvent struct {
	ID         uuid.UUID          `json:"id"`
	AgentRunID uuid.UUID          `json:"agent_run_id"`
	Seq        int32              `json:"seq"`
	Type       string             `json:"type"`
	Payload    []byte             `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type Session struct {
	ID         uuid.UUID          `json:"id"`
	UserID     uuid.UUID          `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
}

type ToolCall struct {
	ID            uuid.UUID          `json:"id"`
	AgentRunID    uuid.UUID          `json:"agent_run_id"`
	Seq           int32              `json:"seq"`
	ToolName      string             `json:"tool_name"`
	Arguments     []byte             `json:"arguments"`
	ResultSummary *string            `json:"result_summary"`
	EvidenceCount int32              `json:"evidence_count"`
	LatencyMs     *int32             `json:"latency_ms"`
	Status        string             `json:"status"`
	Error         *string            `json:"error"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID               uuid.UUID          `json:"id"`
	Email            string             `json:"email"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	Name             *string            `json:"name"`
	AvatarUrl        *string            `json:"avatar_url"`
	GoogleSub        *string            `json:"google_sub"`
	UseDemoWorkspace bool               `json:"use_demo_workspace"`
}

type UserConnection struct {
	ID                    uuid.UUID          `json:"id"`
	UserID                uuid.UUID          `json:"user_id"`
	Source                string             `json:"source"`
	CredentialsCiphertext []byte             `json:"credentials_ciphertext"`
	Identity              []byte             `json:"identity"`
	Status                string             `json:"status"`
	LastError             *string            `json:"last_error"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
}

type UserLlmKey struct {
	UserID        uuid.UUID          `json:"user_id"`
	Provider      string             `json:"provider"`
	KeyCiphertext []byte             `json:"key_ciphertext"`
	KeyLast4      string             `json:"key_last4"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
