// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type AgentRun struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	Query          string             `json:"query"`
	Status         string             `json:"status"`
	Model          *string            `json:"model"`
	Answer         *string            `json:"answer"`
	Error          *string            `json:"error"`
	LatencyMs      *int32             `json:"latency_ms"`
	InputTokens    *int32             `json:"input_tokens"`
	OutputTokens   *int32             `json:"output_tokens"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

type Conversation struct {
	ID        uuid.UUID          `json:"id"`
	UserID    uuid.UUID          `json:"user_id"`
	Title     *string            `json:"title"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type LlmCall struct {
	ID           uuid.UUID          `json:"id"`
	AgentRunID   uuid.UUID          `json:"agent_run_id"`
	Purpose      string             `json:"purpose"`
	Model        string             `json:"model"`
	InputTokens  *int32             `json:"input_tokens"`
	OutputTokens *int32             `json:"output_tokens"`
	LatencyMs    *int32             `json:"latency_ms"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID             uuid.UUID          `json:"id"`
	ConversationID uuid.UUID          `json:"conversation_id"`
	Role           string             `json:"role"`
	Content        string             `json:"content"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type RunEvent struct {
	ID         uuid.UUID          `json:"id"`
	AgentRunID uuid.UUID          `json:"agent_run_id"`
	Seq        int32              `json:"seq"`
	Type       string             `json:"type"`
	Payload    []byte             `json:"payload"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID        uuid.UUID          `json:"id"`
	Email     string             `json:"email"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
