// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CompleteAgentRun(ctx context.Context, arg CompleteAgentRunParams) (AgentRun, error)
	// Used to tell "the index is empty" apart from "this query matched nothing",
	// which are different answers for the agent: the first means stop searching the
	// knowledge base, the second means rephrase.
	CountDocuments(ctx context.Context) (int64, error)
	CountDocumentsBySource(ctx context.Context, source string) (int64, error)
	// Per-source tab counts under the same filters as ListDocuments, so the tabs
	// and the list never disagree.
	CountDocumentsFiltered(ctx context.Context, arg CountDocumentsFilteredParams) ([]CountDocumentsFilteredRow, error)
	// Per-user rate limit: the shared cost of a run is Satyam's upstream
	// API quotas even when the LLM spend is the user's. $2 is a timestamp rather
	// than a hardcoded interval so tests can pin the window.
	CountUserRunsSince(ctx context.Context, arg CountUserRunsSinceParams) (int64, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	DeleteChunksByDocument(ctx context.Context, documentID uuid.UUID) error
	// Opportunistic housekeeping, called on login; there is no background sweeper.
	DeleteExpiredSessions(ctx context.Context) (int64, error)
	DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) (int64, error)
	DeleteUserConnection(ctx context.Context, arg DeleteUserConnectionParams) (int64, error)
	DeleteUserLLMKey(ctx context.Context, userID uuid.UUID) (int64, error)
	FailAgentRun(ctx context.Context, arg FailAgentRunParams) (AgentRun, error)
	// Ownership is enforced in the query, not in Go: GET /api/runs/{id} takes a
	// caller-supplied UUID, and joining through conversations is what stops it
	// being an IDOR the moment a second user exists.
	GetAgentRunForUser(ctx context.Context, arg GetAgentRunForUserParams) (AgentRun, error)
	// Runs don't carry a user_id; ownership lives on the conversation. The worker
	// resolves the owner to build the run's LLM provider from their stored key.
	GetAgentRunOwner(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	// Scoped by user_id on purpose: keeping the ownership predicate in the query
	// means a future handler cannot forget the Go-side check and open an IDOR.
	GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error)
	GetDocumentByID(ctx context.Context, id uuid.UUID) (Document, error)
	GetDocumentBySourceExternalID(ctx context.Context, arg GetDocumentBySourceExternalIDParams) (Document, error)
	// The middleware's single lookup: session validity and the user in one query.
	// Expiry is enforced here, not in Go, so a revoked-or-expired session and an
	// unknown token are indistinguishable to the caller (both are no-rows).
	GetSessionUserByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionUserByTokenHashRow, error)
	GetUserConnection(ctx context.Context, arg GetUserConnectionParams) (UserConnection, error)
	GetUserDemoWorkspace(ctx context.Context, id uuid.UUID) (bool, error)
	GetUserLLMKey(ctx context.Context, userID uuid.UUID) (UserLlmKey, error)
	InsertAgentRun(ctx context.Context, arg InsertAgentRunParams) (AgentRun, error)
	InsertCitation(ctx context.Context, arg InsertCitationParams) (Citation, error)
	// The embedding arrives as pgvector's text form and is cast in SQL. Passing it
	// as text keeps pgx out of the business of knowing the vector type's OID (which
	// is dynamic, since vector comes from an extension) at the cost of one cast per
	// row on a path that is already dominated by the embedding API call.
	InsertDocumentChunk(ctx context.Context, arg InsertDocumentChunkParams) error
	InsertEvalRun(ctx context.Context, arg InsertEvalRunParams) (EvalRun, error)
	// Per-run evidence numbering plus per-run dedupe in one statement.
	//
	// The conflict clause is a deliberate no-op update rather than DO NOTHING: the
	// caller needs the existing row's seq back so a second tool call that surfaces
	// the same document reuses its citation number, and DO NOTHING returns no row at
	// all. Assigning tool_call_id to itself keeps "the call that first surfaced this"
	// intact.
	InsertEvidence(ctx context.Context, arg InsertEvidenceParams) (Evidence, error)
	InsertLLMCall(ctx context.Context, arg InsertLLMCallParams) (LlmCall, error)
	// agent_run_id is null for user messages; the orchestrator sets it on the
	// assistant answer so the frontend can reach the run's trace from the message.
	InsertMessage(ctx context.Context, arg InsertMessageParams) (Message, error)
	// The sequence is computed inside the statement rather than tracked by the
	// caller: a resumed or retried run has no in-process memory of how far the
	// transcript already got, and guessing would collide with the
	// unique (agent_run_id, seq) constraint and abort the whole transaction.
	InsertRunEvent(ctx context.Context, arg InsertRunEventParams) (RunEvent, error)
	// seq is computed inside the statement, exactly as InsertRunEvent does: a run
	// retried after a worker crash has no in-process memory of how many tool calls
	// it already recorded, and guessing would collide with the unique
	// (agent_run_id, seq) constraint.
	InsertToolCall(ctx context.Context, arg InsertToolCallParams) (ToolCall, error)
	// Joined with evidence because a citation is only meaningful alongside what it
	// points at: the trace endpoint renders the marker, the claim, and the source's
	// title and URL together.
	// Ordered by the marker's number, not by evidence.seq: the markers are what a
	// reader follows through the answer ([1], [2], [3]), while evidence.seq is
	// discovery order and does not match. A plain text sort would put [10] before
	// [2], hence the cast.
	ListCitationsByRun(ctx context.Context, agentRunID uuid.UUID) ([]ListCitationsByRunRow, error)
	ListConversationsByUser(ctx context.Context, userID uuid.UUID) ([]Conversation, error)
	// The Sources view listing. Both filters are optional (NULL disables them);
	// ILIKE over title/content is deliberate — 121 docs need no FTS index, and the
	// snippet windowing happens in Go where it can be rune-safe.
	ListDocuments(ctx context.Context, arg ListDocumentsParams) ([]ListDocumentsRow, error)
	ListEvalRuns(ctx context.Context) ([]EvalRun, error)
	ListEvidenceByRun(ctx context.Context, agentRunID uuid.UUID) ([]Evidence, error)
	ListMessagesByConversation(ctx context.Context, conversationID uuid.UUID) ([]Message, error)
	// Ordered by seq, not created_at: two events written inside one transaction can
	// share a timestamp, and the transcript's order is the thing being replayed.
	ListRunEventsByRun(ctx context.Context, agentRunID uuid.UUID) ([]RunEvent, error)
	// The SSE stream's incremental read: everything the client has not seen yet.
	// seq > $2 with $2 = 0 is the full transcript, so first attach and resume are
	// the same query.
	ListRunEventsByRunAfterSeq(ctx context.Context, arg ListRunEventsByRunAfterSeqParams) ([]RunEvent, error)
	ListToolCallsByRun(ctx context.Context, agentRunID uuid.UUID) ([]ToolCall, error)
	ListUserConnections(ctx context.Context, userID uuid.UUID) ([]UserConnection, error)
	// The join is the point: the vector index finds the chunk, and the
	// relational half supplies the title, URL and metadata that make it citable.
	// Doing both in one query is only possible because the vectors live in the same
	// Postgres as everything else.
	//
	// <=> is cosine DISTANCE (0 = identical), so similarity is 1 - distance and the
	// ordering is ascending. The operator must match the index's vector_cosine_ops
	// or the planner silently ignores the index.
	SearchDocumentChunks(ctx context.Context, arg SearchDocumentChunksParams) ([]SearchDocumentChunksRow, error)
	SetUserConnectionError(ctx context.Context, arg SetUserConnectionErrorParams) error
	SetUserDemoWorkspace(ctx context.Context, arg SetUserDemoWorkspaceParams) error
	// Last content change per source (updated_at only moves when content_hash
	// changes) — distinct from "last refreshed", which comes from River job rows.
	SourceLastIndexed(ctx context.Context) ([]SourceLastIndexedRow, error)
	// Claims a queued run. The status guard makes the transition idempotent for a
	// River job that is retried after a worker crash (still 'running'), while
	// refusing to restart a run that already reached a terminal state — returning
	// no rows is the signal to skip.
	StartAgentRun(ctx context.Context, id uuid.UUID) (AgentRun, error)
	TouchConversation(ctx context.Context, id uuid.UUID) error
	TouchSession(ctx context.Context, id uuid.UUID) error
	// Called only for documents whose content_hash actually changed (the indexer
	// short-circuits before this on an unchanged hash), so the update branch always
	// has work to do.
	UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (Document, error)
	// Conflict on email, not google_sub: a pre-existing row (the dev user, say)
	// gains its Google identity on first login instead of duplicating the account.
	UpsertGoogleUser(ctx context.Context, arg UpsertGoogleUserParams) (User, error)
	// Idempotent by email: returns the existing row when the user already exists.
	UpsertUser(ctx context.Context, email string) (User, error)
	// One connection per (user, source): reconnecting replaces the credential and
	// clears any error state in the same write.
	UpsertUserConnection(ctx context.Context, arg UpsertUserConnectionParams) (UserConnection, error)
	// One key per user: replacing the key or switching provider is the same write.
	UpsertUserLLMKey(ctx context.Context, arg UpsertUserLLMKeyParams) (UserLlmKey, error)
}

var _ Querier = (*Queries)(nil)
