// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_events.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const insertRunEvent = `-- name: InsertRunEvent :one
INSERT INTO run_events (agent_run_id, seq, type, payload)
VALUES ($1, $2, $3, $4)
RETURNING id, agent_run_id, seq, type, payload, created_at
`

type InsertRunEventParams struct {
	AgentRunID uuid.UUID `json:"agent_run_id"`
	Seq        int32     `json:"seq"`
	Type       string    `json:"type"`
	Payload    []byte    `json:"payload"`
}

func (q *Queries) InsertRunEvent(ctx context.Context, arg InsertRunEventParams) (RunEvent, error) {
	row := q.db.QueryRow(ctx, insertRunEvent,
		arg.AgentRunID,
		arg.Seq,
		arg.Type,
		arg.Payload,
	)
	var i RunEvent
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.Seq,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}
