// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: run_events.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const insertRunEvent = `-- name: InsertRunEvent :one
INSERT INTO run_events (agent_run_id, seq, type, payload)
SELECT $1, coalesce(max(seq), 0) + 1, $2, $3
FROM run_events
WHERE agent_run_id = $1
RETURNING id, agent_run_id, seq, type, payload, created_at
`

type InsertRunEventParams struct {
	AgentRunID uuid.UUID `json:"agent_run_id"`
	Type       string    `json:"type"`
	Payload    []byte    `json:"payload"`
}

// The sequence is computed inside the statement rather than tracked by the
// caller: a resumed or retried run has no in-process memory of how far the
// transcript already got, and guessing would collide with the
// unique (agent_run_id, seq) constraint and abort the whole transaction.
func (q *Queries) InsertRunEvent(ctx context.Context, arg InsertRunEventParams) (RunEvent, error) {
	row := q.db.QueryRow(ctx, insertRunEvent, arg.AgentRunID, arg.Type, arg.Payload)
	var i RunEvent
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.Seq,
		&i.Type,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listRunEventsByRun = `-- name: ListRunEventsByRun :many
SELECT id, agent_run_id, seq, type, payload, created_at FROM run_events
WHERE agent_run_id = $1
ORDER BY seq
`

// Ordered by seq, not created_at: two events written inside one transaction can
// share a timestamp, and the transcript's order is the thing being replayed.
func (q *Queries) ListRunEventsByRun(ctx context.Context, agentRunID uuid.UUID) ([]RunEvent, error) {
	rows, err := q.db.Query(ctx, listRunEventsByRun, agentRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RunEvent{}
	for rows.Next() {
		var i RunEvent
		if err := rows.Scan(
			&i.ID,
			&i.AgentRunID,
			&i.Seq,
			&i.Type,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
