// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions (user_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, user_id, token_hash, created_at, expires_at, last_seen_at
`

type CreateSessionParams struct {
	UserID    uuid.UUID          `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, createSession, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
	)
	return i, err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :execrows
DELETE FROM sessions WHERE expires_at <= now()
`

// Opportunistic housekeeping, called on login; there is no background sweeper.
func (q *Queries) DeleteExpiredSessions(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredSessions)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteSessionByTokenHash = `-- name: DeleteSessionByTokenHash :execrows
DELETE FROM sessions WHERE token_hash = $1
`

func (q *Queries) DeleteSessionByTokenHash(ctx context.Context, tokenHash []byte) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSessionByTokenHash, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSessionUserByTokenHash = `-- name: GetSessionUserByTokenHash :one
SELECT s.id AS session_id, s.last_seen_at, s.expires_at,
       u.id AS user_id, u.email, u.name, u.avatar_url
FROM sessions s
JOIN users u ON u.id = s.user_id
WHERE s.token_hash = $1 AND s.expires_at > now()
`

type GetSessionUserByTokenHashRow struct {
	SessionID  uuid.UUID          `json:"session_id"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	UserID     uuid.UUID          `json:"user_id"`
	Email      string             `json:"email"`
	Name       *string            `json:"name"`
	AvatarUrl  *string            `json:"avatar_url"`
}

// The middleware's single lookup: session validity and the user in one query.
// Expiry is enforced here, not in Go, so a revoked-or-expired session and an
// unknown token are indistinguishable to the caller (both are no-rows).
func (q *Queries) GetSessionUserByTokenHash(ctx context.Context, tokenHash []byte) (GetSessionUserByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getSessionUserByTokenHash, tokenHash)
	var i GetSessionUserByTokenHashRow
	err := row.Scan(
		&i.SessionID,
		&i.LastSeenAt,
		&i.ExpiresAt,
		&i.UserID,
		&i.Email,
		&i.Name,
		&i.AvatarUrl,
	)
	return i, err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
