// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tool_calls.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const insertToolCall = `-- name: InsertToolCall :one
INSERT INTO tool_calls (agent_run_id, seq, tool_name, arguments, result_summary,
                        evidence_count, latency_ms, status, error)
SELECT $1::uuid,
       coalesce(max(seq), 0) + 1,
       $2::text,
       $3::jsonb,
       $4::text,
       $5::int,
       $6::int,
       $7::text,
       $8::text
FROM tool_calls
WHERE agent_run_id = $1::uuid
RETURNING id, agent_run_id, seq, tool_name, arguments, result_summary, evidence_count, latency_ms, status, error, created_at
`

type InsertToolCallParams struct {
	AgentRunID    uuid.UUID `json:"agent_run_id"`
	ToolName      string    `json:"tool_name"`
	Arguments     []byte    `json:"arguments"`
	ResultSummary *string   `json:"result_summary"`
	EvidenceCount int32     `json:"evidence_count"`
	LatencyMs     *int32    `json:"latency_ms"`
	Status        string    `json:"status"`
	Error         *string   `json:"error"`
}

// seq is computed inside the statement, exactly as InsertRunEvent does: a run
// retried after a worker crash has no in-process memory of how many tool calls
// it already recorded, and guessing would collide with the unique
// (agent_run_id, seq) constraint.
func (q *Queries) InsertToolCall(ctx context.Context, arg InsertToolCallParams) (ToolCall, error) {
	row := q.db.QueryRow(ctx, insertToolCall,
		arg.AgentRunID,
		arg.ToolName,
		arg.Arguments,
		arg.ResultSummary,
		arg.EvidenceCount,
		arg.LatencyMs,
		arg.Status,
		arg.Error,
	)
	var i ToolCall
	err := row.Scan(
		&i.ID,
		&i.AgentRunID,
		&i.Seq,
		&i.ToolName,
		&i.Arguments,
		&i.ResultSummary,
		&i.EvidenceCount,
		&i.LatencyMs,
		&i.Status,
		&i.Error,
		&i.CreatedAt,
	)
	return i, err
}

const listToolCallsByRun = `-- name: ListToolCallsByRun :many
SELECT id, agent_run_id, seq, tool_name, arguments, result_summary, evidence_count, latency_ms, status, error, created_at FROM tool_calls
WHERE agent_run_id = $1
ORDER BY seq
`

func (q *Queries) ListToolCallsByRun(ctx context.Context, agentRunID uuid.UUID) ([]ToolCall, error) {
	rows, err := q.db.Query(ctx, listToolCallsByRun, agentRunID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ToolCall{}
	for rows.Next() {
		var i ToolCall
		if err := rows.Scan(
			&i.ID,
			&i.AgentRunID,
			&i.Seq,
			&i.ToolName,
			&i.Arguments,
			&i.ResultSummary,
			&i.EvidenceCount,
			&i.LatencyMs,
			&i.Status,
			&i.Error,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
