// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_llm_keys.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserLLMKey = `-- name: DeleteUserLLMKey :execrows
DELETE FROM user_llm_keys WHERE user_id = $1
`

func (q *Queries) DeleteUserLLMKey(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserLLMKey, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserLLMKey = `-- name: GetUserLLMKey :one
SELECT user_id, provider, key_ciphertext, key_last4, created_at, updated_at FROM user_llm_keys WHERE user_id = $1
`

func (q *Queries) GetUserLLMKey(ctx context.Context, userID uuid.UUID) (UserLlmKey, error) {
	row := q.db.QueryRow(ctx, getUserLLMKey, userID)
	var i UserLlmKey
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.KeyCiphertext,
		&i.KeyLast4,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserLLMKey = `-- name: UpsertUserLLMKey :one
INSERT INTO user_llm_keys (user_id, provider, key_ciphertext, key_last4)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id) DO UPDATE
    SET provider       = excluded.provider,
        key_ciphertext = excluded.key_ciphertext,
        key_last4      = excluded.key_last4,
        updated_at     = now()
RETURNING user_id, provider, key_ciphertext, key_last4, created_at, updated_at
`

type UpsertUserLLMKeyParams struct {
	UserID        uuid.UUID `json:"user_id"`
	Provider      string    `json:"provider"`
	KeyCiphertext []byte    `json:"key_ciphertext"`
	KeyLast4      string    `json:"key_last4"`
}

// One key per user: replacing the key or switching provider is the same write.
func (q *Queries) UpsertUserLLMKey(ctx context.Context, arg UpsertUserLLMKeyParams) (UserLlmKey, error) {
	row := q.db.QueryRow(ctx, upsertUserLLMKey,
		arg.UserID,
		arg.Provider,
		arg.KeyCiphertext,
		arg.KeyLast4,
	)
	var i UserLlmKey
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.KeyCiphertext,
		&i.KeyLast4,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
