// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_connections.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deleteUserConnection = `-- name: DeleteUserConnection :execrows
DELETE FROM user_connections WHERE user_id = $1 AND source = $2
`

type DeleteUserConnectionParams struct {
	UserID uuid.UUID `json:"user_id"`
	Source string    `json:"source"`
}

func (q *Queries) DeleteUserConnection(ctx context.Context, arg DeleteUserConnectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUserConnection, arg.UserID, arg.Source)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserConnection = `-- name: GetUserConnection :one
SELECT id, user_id, source, credentials_ciphertext, identity, status, last_error, created_at, updated_at FROM user_connections WHERE user_id = $1 AND source = $2
`

type GetUserConnectionParams struct {
	UserID uuid.UUID `json:"user_id"`
	Source string    `json:"source"`
}

func (q *Queries) GetUserConnection(ctx context.Context, arg GetUserConnectionParams) (UserConnection, error) {
	row := q.db.QueryRow(ctx, getUserConnection, arg.UserID, arg.Source)
	var i UserConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.CredentialsCiphertext,
		&i.Identity,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserDemoWorkspace = `-- name: GetUserDemoWorkspace :one
SELECT use_demo_workspace FROM users WHERE id = $1
`

func (q *Queries) GetUserDemoWorkspace(ctx context.Context, id uuid.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getUserDemoWorkspace, id)
	var use_demo_workspace bool
	err := row.Scan(&use_demo_workspace)
	return use_demo_workspace, err
}

const listUserConnections = `-- name: ListUserConnections :many
SELECT id, user_id, source, credentials_ciphertext, identity, status, last_error, created_at, updated_at FROM user_connections WHERE user_id = $1 ORDER BY source
`

func (q *Queries) ListUserConnections(ctx context.Context, userID uuid.UUID) ([]UserConnection, error) {
	rows, err := q.db.Query(ctx, listUserConnections, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserConnection{}
	for rows.Next() {
		var i UserConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Source,
			&i.CredentialsCiphertext,
			&i.Identity,
			&i.Status,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserConnectionError = `-- name: SetUserConnectionError :exec
UPDATE user_connections
SET status = 'error', last_error = $3, updated_at = now()
WHERE user_id = $1 AND source = $2
`

type SetUserConnectionErrorParams struct {
	UserID    uuid.UUID `json:"user_id"`
	Source    string    `json:"source"`
	LastError *string   `json:"last_error"`
}

func (q *Queries) SetUserConnectionError(ctx context.Context, arg SetUserConnectionErrorParams) error {
	_, err := q.db.Exec(ctx, setUserConnectionError, arg.UserID, arg.Source, arg.LastError)
	return err
}

const setUserDemoWorkspace = `-- name: SetUserDemoWorkspace :exec
UPDATE users SET use_demo_workspace = $2 WHERE id = $1
`

type SetUserDemoWorkspaceParams struct {
	ID               uuid.UUID `json:"id"`
	UseDemoWorkspace bool      `json:"use_demo_workspace"`
}

func (q *Queries) SetUserDemoWorkspace(ctx context.Context, arg SetUserDemoWorkspaceParams) error {
	_, err := q.db.Exec(ctx, setUserDemoWorkspace, arg.ID, arg.UseDemoWorkspace)
	return err
}

const upsertUserConnection = `-- name: UpsertUserConnection :one
INSERT INTO user_connections (user_id, source, credentials_ciphertext, identity)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, source) DO UPDATE
    SET credentials_ciphertext = excluded.credentials_ciphertext,
        identity               = excluded.identity,
        status                 = 'active',
        last_error             = NULL,
        updated_at             = now()
RETURNING id, user_id, source, credentials_ciphertext, identity, status, last_error, created_at, updated_at
`

type UpsertUserConnectionParams struct {
	UserID                uuid.UUID `json:"user_id"`
	Source                string    `json:"source"`
	CredentialsCiphertext []byte    `json:"credentials_ciphertext"`
	Identity              []byte    `json:"identity"`
}

// One connection per (user, source): reconnecting replaces the credential and
// clears any error state in the same write.
func (q *Queries) UpsertUserConnection(ctx context.Context, arg UpsertUserConnectionParams) (UserConnection, error) {
	row := q.db.QueryRow(ctx, upsertUserConnection,
		arg.UserID,
		arg.Source,
		arg.CredentialsCiphertext,
		arg.Identity,
	)
	var i UserConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Source,
		&i.CredentialsCiphertext,
		&i.Identity,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
