// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package store

import (
	"context"
)

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (email)
VALUES ($1)
ON CONFLICT (email) DO UPDATE SET email = EXCLUDED.email
RETURNING id, email, created_at
`

// Idempotent by email: returns the existing row when the user already exists.
func (q *Queries) UpsertUser(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser, email)
	var i User
	err := row.Scan(&i.ID, &i.Email, &i.CreatedAt)
	return i, err
}
